version: '3.8'

services:
  roundcube:
    image: roundcube/roundcubemail:latest
    container_name: roundcube
    restart: always
    environment:
      ROUNDCUBEMAIL_DEFAULT_HOST: central-mariadb
      ROUNDCUBEMAIL_SMTP_SERVER: smtp.example.com
      ROUNDCUBEMAIL_DES_KEY: some_secret_key
      ROUNDCUBEMAIL_DB_TYPE: mysql
      ROUNDCUBEMAIL_DB_HOST: central-mariadb
      ROUNDCUBEMAIL_DB_USER: central_user
      ROUNDCUBEMAIL_DB_PASSWORD: your_password
      ROUNDCUBEMAIL_DB_NAME: central_db
    ports:
      - "80:80"
    networks:
      - central-net
    volumes:
      - roundcube_data:/var/www/html

networks:
  central-net:
    external: true

volumes:
  roundcube_data:
