version: '3.8'

services:
  roundcube:
    image: roundcube/roundcubemail:latest
    container_name: roundcube
    restart: always
    environment:
      ROUNDCUBEMAIL_DEFAULT_HOST: mail.arqaamtech.com
      ROUNDCUBEMAIL_SMTP_SERVER: smtp.arqaamtech.com
      ROUNDCUBEMAIL_DES_KEY: some_secret_key
      ROUNDCUBEMAIL_DB_TYPE: mysql
      ROUNDCUBEMAIL_DB_HOST: central-mariadb
      ROUNDCUBEMAIL_DB_USER: admin
      ROUNDCUBEMAIL_DB_PASSWORD: Admin@2014
      ROUNDCUBEMAIL_DB_NAME: emails
    ports:
      - "8088:80"
    networks:
      - central-net
    volumes:
      - roundcube_data:/var/www/html

networks:
  central-net:
    external: true

volumes:
  roundcube_data:
