version: '3.8'

services:
  flowy:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /root/flowy:/app
      #- /Users/omar/Desktop/dev/Flowy:/app
    ports:
      - '3001:3001'
    environment:
      #- NODE_ENV=development
      - PORT=3001
    networks:
      - central-net

networks:
  central-net:
    external: true