version: '3'

services:
  redis:
    image: redis:alpine
    restart: always
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - redis:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "128M"

  front:
    image: ghcr.io/mailu/nginx:2.0
    restart: always
    env_file: .env
    ports:
      - "8088:80"
      - "443:443"
      - "25:25"
      - "465:465"
      - "587:587"
      - "110:110"
      - "995:995"
      - "143:143"
      - "993:993"
      - "4190:4190"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "256M"
    volumes:
      - mailu:/data

  admin:
    image: ghcr.io/mailu/admin:2.0
    restart: always
    env_file: .env
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "256M"
    volumes:
      - mailu:/data

  imap:
    image: ghcr.io/mailu/dovecot:2.0
    restart: always
    env_file: .env
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "256M"
    volumes:
      - mailu:/data

  smtp:
    image: ghcr.io/mailu/postfix:2.0
    restart: always
    env_file: .env
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "256M"
    volumes:
      - mailu:/data

volumes:
  redis:
  mailu:
