version: '3.8'

services:
  app:
    image: php:7.3-fpm
    container_name: php_app
    working_dir: /var/www
    volumes:
      - ./worketic:/root/www/worketic
      - ./wordpress:/root/www/wordpress
    ports:
      - "9000:9000"
    networks:
      - central-net

volumes:
  db_data:

networks:
  central-net:
    external: true
