version: '3.8'

services:
  php_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_app
    ports:
      - "8000:80"
    volumes:
      - /root/www:/var/www/
    networks:
      - central-net
      
volumes:
  db_data:
